plugins {
    id 'java'
    id 'application'
}

group = 'edu.ucse'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    // Sin dependencias externas — todo es Java estándar (java.util.function, java.util.stream)
}

application {
    mainClass = 'funcional.Main'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}
